name: FeroxCore
version: '${project.version}'
author: Marijn2341
main: be.marijn2341.feroxcore.Main

depend:
  - NametagEdit

softdepend:
  - Multiverse-Core

commands:
  test:
    description: No description.
  skipmap:
    description: You can skip a game with this command.
  loadmaps:
    description: Load all the maps without restarting.
  lobby:
    description: The plugin will bring you to the lobby.
  verify:
    description: You will receive a code to verify yourself on discord.
  startgame:
    description: You can start a game with this command.

permissions:
  ferox.admin:
    default: op
  ferox.lobby.build:
    default: op
